spring:
  datasource:
    url: jdbc:mysql://mysql:3306/heritage?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
server:
  port: 8080
app:
  uploadDir: "/app/uploads"
  ffmpeg:
    path: ffmpeg
    hlsTime: 6
